name: "Construção do artefato"

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push docker image
      uses: docker/build-push-action@v6
      with:
        push: true
        context: .
        file: ./Dockerfile
        tags: |
          ${{ secrets.DOCKER_HUB_USER }}/go_ci:latest
          ${{ secrets.DOCKER_HUB_USER }}/go_ci:${{ github.sha }}